// @ts-ignore
import zhLocale from 'grapesjs/locale/zh.mjs';

export default {
  ...zhLocale,
  blockManager: {
    notFound: '没有找到组件',
    blocks: '组件',
    add: '添加更多组件',
    search: '搜索...',
    types: {
      regular: '普通组件',
      symbols: '符号组件',
    },
    symbols: {
      notFound: '没有找到符号组件',
      instancesProject: '项目中的实例/s',
      delete: '删除符号组件',
      deleteConfirm: '确定要删除符号组件吗？所有项目中的实例将被分离。',
    },
  },
  globalStyleManager: {
    notFound: '没有找到全局样式',
  },
  templates: {
    notFound: '没有找到模板',
  },
  fontManager: {
    addFontToProject: '添加字体到项目',
    projectFonts: '项目字体',
    emptyProjectFonts: '项目中没有字体。',
    selectFont: '选择字体',
  },
  dataSources: {
    confirm: '确认',
    clearDataValue: '清除数据值',
    connectDataValue: '连接数据值',
    variable: '变量',
    defaultValue: '默认值',
    variablePath: '变量路径',
    selectVariablePath: '选择变量路径',
    openPathExplorer: '打开路径浏览器',
    closePathExplorer: '关闭路径浏览器',
    toggleResolvedPath: '切换解析路径',
    items: '{length} 项/s',
    properties: '{length} 属性/s',
    editVariable: '编辑变量',
    editCondition: '编辑条件',
    editCollection: '编辑集合',
    condition: '条件',
    conditionTrue: 'True 条件',
    conditionFalse: 'False 条件',
    conditionAnd: 'AND',
    conditionOr: 'OR',
    conditionElse: 'Else',
    addCondition: '添加条件',
    deleteCondition: '删除条件',
    operator: '运算符',
    leftValue: '左值',
    rightValue: '右值',
    ifTrue: 'True 值',
    ifFalse: 'False 值',
    valueTrue: 'True',
    valueFalse: 'False',
    collection: '集合',
    collectionItem: '集合项',
    collectionId: '集合 ID',
    collectionStartIndex: '开始索引',
    collectionEndIndex: '结束索引',
    collectionUpToEndIndex: '所有',
    operators: {
      '=': '= (等于)',
      '!=': '!= (不等于)',
      '>': '> (大于)',
      '>=': '>= (大于等于)',
      '<': '< (小于)',
      '<=': '<= (小于等于)',
      contains: '包含',
      startsWith: '以...开头',
      endsWith: '以...结尾',
      matchesRegex: '匹配正则表达式',
      equalsIgnoreCase: '等于 (忽略大小写)',
      trimEquals: '修剪后等于',
      and: 'AND',
      or: 'OR',
      xor: 'XOR',
      equals: '等于',
      isDefined: '已定义',
      isNull: '为空',
      isUndefined: '未定义',
      isTruthy: '为真',
      isFalsy: '为假',
      isDefaultValue: '为默认值',
      isArray: '为数组',
      isObject: '为对象',
      isString: '为字符串',
      isNumber: '为数字',
      isBoolean: '为布尔值',
    },
  },
};
